export const membershipType = [
  'ProLicense',
  'General Education',
  'New Member',
  'Orientation',
  'Events',
  'Records',
  'Banking/Treasury',
  'Oversight',
  'Ombudsman',
  'Vetting',
  'General Elections',
  'Office of Marshal At Arms',
  'IT Infrastructure',
  'Court Venue',
  'Jury Pool',
  'Court Oversight',
  'Sheriff',
  'Coroner Office',
  'Litigation',
  'Land Patent',
  'International Education',
  'Provision',
  'Militia Education',
  'Militia Operation',
  'Accounting',
  'Armory',
  'Bookkeeping',
  'Carpentry',
  'Childcare',
  'Computer Programming',
  'Construction',
  'Cooking',
  'Denistry',
  'Education',
  'Electrician',
  'Electronics Repair',
  'Farming',
  'IT',
  'Janitorial',
  'Marketing',
  'Medical',
  'Nutrition/Dietary',
  'Organizing',
  'Plumbing',
  'Public Relations',
  'Radio Communications',
  'Ranching',
  'Recordkeeping',
  'Research',
  'Sewing',
  'Teaching',
  'Transportation',
  'Woodworking',
];

export const county = [
  'Adams',
  'Allen',
  'Ashland',
  'Ashtabula',
  'Athens',
  'Auglaize',
  'Belmont',
  'Brown',
  'Butler',
  'Carroll',
  'Champaign',
  'Clark',
  'Clermont',
  'Clinton',
  'Columbiana',
  'Coshocton',
  'Crawford',
  'Cuyahoga',
  'Darke',
  'Defiance',
  'Delaware',
  'Erie',
  'Fairfield',
  'Fayette',
  'Franklin',
  'Fulton',
  'Gallia',
  'Geauga',
  'Greene',
  'Guernsey',
  'Hamilton',
  'Hancock',
  'Hardin',
  'Harrison',
  'Henry',
  'Highland',
  'Hocking',
  'Holmes',
  'Huron',
  'Jackson',
  'Jefferson',
  'Knox',
  'Lake',
  'Lawrence',
  'Licking',
  'Logan',
  'Lorain',
  'Lucas',
  'Madison',
  'Mahoning',
  'Marion',
  'Medina',
  'Meigs',
  'Mercer',
  'Miami',
  'Monroe',
  'Montgomery',
  'Morgan',
  'Morrow',
  'Muskingum',
  'Noble',
  'Ottawa',
  'Paulding',
  'Perry',
  'Pickaway',
  'Pike',
  'Portage',
  'Preble',
  'Putnam',
  'Richland',
  'Ross',
  'Sandusky',
  'Scioto',
  'Seneca',
  'Shelby',
  'Stark',
  'Summit',
  'Trumbull',
  'Tuscarawas',
  'Union',
  'Van Wert',
  'Vinton',
  'Warren',
  'Washington',
  'Wayne',
  'Williams',
  'Wood ',
  'Wyandot',
];

export const statusDocument = [
  'Declaration Born within Physical Borders of 50 States',
  'Declaration Born in DC-US Territory-Military Base',
  'Declaration For Federal Persons',
  'Declaration For Naturalized/Green Card Immigrants',
  'Declaration Undocumented Immigrants',
  'Declaration of Political Status',
  'Birth Record',
  'Witness Testimony01',
  'Witness Testimony02',
  'Voter Cancellation',
  'Revocation of Election to Pay Taxes-IRS',
  'Revocation of Election to Pay Taxes-IRO',
  'Notice of Distraint & Levy',
  'Letter of Status-SOSUS',
  'Military Severance',
  'Deed of Reconveyance',
  'Certificate of Assumed Names',
  'Act of Expatriation01',
  'Act of Expatriation02',
  'Act of Expatriation03',
  'Cancellation Power of Attorney',
  'Extended Cancellation Power of Attorney',
  'Foreign Sovereign Immunites Act',
  'DNA Paramont Claim',
  'Common Carry Declaration',
  'Diagram of Fraud',
  'Fee Schedule',
  'Lineage Treaty',
  'Marriage Record',
  'BabyDeed01',
  'BabyDeed02',
  'BabyDeed03',
  'BabyDeed04',
  'BabyDeed05',
  'BabyDeed06',
  'BabyDeed07',
  'BabyDeed08',
  'Death Record',
  'Private Business Documents',
];

export const notices = [
  'Notices Upload'
]

export const landPatent = [
'Land Patent01',
'Land Patent02',
'Land Patent03',
'Land Patent04',
'Land Patent05',

]

export const incidentReport = [
'Territorial Government (USA)',
'Municipal  Government (US/STATE/Muni)',
'Commercial Entities',
]

export const privateDocs = [
  'Common Law Will'
]

export const officials = [
'Nationality',
'Status',
'Recording Number',
'Master Record',
'Date Account  Created',
'Date Updated',
'Print Credential Card Date',
'Master Credential Card Number',
'Verified ',
'Paid Credential Card',
'Deceased Date',

]