export const membershipType = [
  'ProLicense',
  'General Education',
  'New Member',
  'Orientation',
  'Events',
  'Records',
  'Banking/Treasury',
  'Oversight',
  'Ombudsman',
  'Vetting',
  'General Elections',
  'Office of Marshal At Arms',
  'IT Infrastructure',
  'Court Venue',
  'Jury Pool',
  'Court Oversight',
  'Sheriff',
  'Coroner Office',
  'Litigation',
  'Land Patent',
  'International Education',
  'Provision',
  'Militia Education',
  'Militia Operation',
  'Accounting',
  'Armory',
  'Bookkeeping',
  'Carpentry',
  'Childcare',
  'Computer Programming',
  'Construction',
  'Cooking',
  'Denistry',
  'Education',
  'Electrician',
  'Electronics Repair',
  'Farming',
  'IT',
  'Janitorial',
  'Marketing',
  'Medical',
  'Nutrition/Dietary',
  'Organizing',
  'Plumbing',
  'Public Relations',
  'Radio Communications',
  'Ranching',
  'Recordkeeping',
  'Research',
  'Sewing',
  'Teaching',
  'Transportation',
  'Woodworking',
];
